version: "3.0"
services:  
  app:
    #build:
      #context:./
       ###  # dockerfile: ./app.dockerfile       
  
    image: bitnami/laravel:latest
    restart: unless-stopped
    networks:
      - basicne
    container_name: laravelapp
    ports: 
      - 8080:8080
     ## external: true 
     ## name: basicne
    volumes:
      - ./:/var/www
#########################     
  web:
    build:
      context: ./ 
 ####   dockerfile: ./web.dockerfile      
    image: nginx:latest
    #depends_on:
     # - app
    ##conatiner_name: nginxapp
## we can add always
    restart: unless-stopped
    ports: 
       - 80:80
       - 443:443
    networks:
      - basicne
    volumes:
      - ./:/var/www/html
###########################
  database:
    build:
      context: .
      
    image: mysql:latest
   # restart: always
 #   restart: unless_stopped
    ports:
      - 3302:3306
      - 33090:33060 
    networks:
        - basicne   
    depends_on:
      - app
    #volumes:
     # - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "OSMAMdb"
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_PASSWORD: "12345"
      MYSQL_USER: root\
      TZ: Asia/Riyadh    
#########################
networks:
  basicne:
    driver: bridge        

#volumes: 
  #- dbdata: 
   #   driver: local
